//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuffmanCoding
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int STT { get; set; }
        public string TruocMaHoa { get; set; }
        public string SauMaHoa { get; set; }
    }
}
